{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": false,
  "node_js": [
    "node"
  ],
  "script": [
    "npm run lint",
    "npm run test:coveralls"
  ],
  "notifications": {
    "email": [
      {
        "enabled": false
      }
    ]
  }
}